import numpy as np 


In [1]:
import numpy as np 


In [2]:
data = np.array([[1,1,1],[2,2,2],[3,3,3]])
data

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [3]:
vector = np.array([1,2,3])

In [4]:
data/vector

array([[1.        , 0.5       , 0.33333333],
       [2.        , 1.        , 0.66666667],
       [3.        , 1.5       , 1.        ]])

In [23]:
threeD_data = np.array( [[[1,1,1],[2,2,2],[3,3,3]],[[1,1,1],[2,2,2],[3,3,3]],[[1,1,1],[2,2,2],[3,3,3]],[[5,5,5],[2,2,2],[6,3,6]]]
)
threeD_data.shape

(4, 3, 3)

In [16]:
threeD_data

array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]])

In [26]:
vector = np.array([[2,1,2],[0,0,0],[1,1,1]]) 
vector


array([[2, 1, 2],
       [0, 0, 0],
       [1, 1, 1]])

In [27]:
np.divide(threeD_data,vector)

c:\ProgramData\Anaconda3\envs\CT4D\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[[0.5, 1. , 0.5],
        [inf, inf, inf],
        [3. , 3. , 3. ]],

       [[0.5, 1. , 0.5],
        [inf, inf, inf],
        [3. , 3. , 3. ]],

       [[0.5, 1. , 0.5],
        [inf, inf, inf],
        [3. , 3. , 3. ]],

       [[2.5, 5. , 2.5],
        [inf, inf, inf],
        [6. , 3. , 6. ]]])

In [28]:
threeD_data.ndim

3